
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kebpqrchfnzamwtseeqk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtlYnBxcmNoZm56YW13dHNlZXFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NDEzNDAsImV4cCI6MjA2MzMxNzM0MH0._c1sXc-AwTfcpDPL53AbRKbadm_lHHPdtgqmgA_-Fj0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper type to make table types easier to use
export type TableRow<T extends keyof Database['public']['Tables']> = 
  Database['public']['Tables'][T]['Row'];
